const { onRequest } = require("firebase-functions/v2/https");
const admin = require("firebase-admin");
const express = require('express');
const cors = require('cors');
const axios = require('axios');
const crypto = require('crypto');

// Initialize Firebase Admin for Firestore access
admin.initializeApp();
const db = admin.firestore();

const app = express();
// Automatically allow cross-origin requests
app.use(cors({ origin: true }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const MERCHANT_ID = process.env.PHONEPE_MERCHANT_ID || "PGTESTPAYUAT86";
const SALT_KEY = process.env.PHONEPE_SALT_KEY || "96434309-7796-489d-8924-ab56988a6076";
const SALT_INDEX = process.env.PHONEPE_SALT_INDEX || 1;
const ENV = process.env.PHONEPE_ENV || 'UAT';
const CLIENT_URL = 'https://pickles-gilt.vercel.app';
// The backend URL will be routed via Firebase Hosting rewrites
const BACKEND_URL = `${CLIENT_URL}/api`;

const PHONEPE_HOST = ENV === 'PROD' 
    ? 'https://api.phonepe.com/apis/hermes' 
    : 'https://api-preprod.phonepe.com/apis/pg-sandbox';

// Helper to update order in Firestore
async function updateOrderStatus(transactionId, status, orderData = null) {
    try {
        const orderRef = db.collection('orders').doc(transactionId);
        if (orderData) {
            await orderRef.set({
                ...orderData,
                status: status,
                updatedAt: admin.firestore.FieldValue.serverTimestamp()
            }, { merge: true });
        } else {
            await orderRef.update({
                status: status,
                updatedAt: admin.firestore.FieldValue.serverTimestamp()
            });
        }
        console.log(`Order ${transactionId} updated to ${status}`);
    } catch (error) {
        console.error("Error updating order in Firestore:", error.message);
    }
}

app.post('/create-payment', async (req, res) => {
    try {
        const { amount, name, phone, address, giftMessage, orderInfo, firestoreId } = req.body;
        
        // Use the Firestore document ID generated by the frontend, or create a new one
        const transactionId = firestoreId || "TXN" + Date.now();
        
        // Initial save to Firestore
        await updateOrderStatus(transactionId, 'PENDING', {
            name, phone, amount, address, giftMessage, orderInfo,
            createdAt: admin.firestore.FieldValue.serverTimestamp()
        });

        let validPhone = phone ? phone.toString().replace(/\D/g, '') : '';
        if (validPhone.length > 10) validPhone = validPhone.slice(-10);

        const payload = {
            merchantId: MERCHANT_ID,
            merchantTransactionId: transactionId,
            merchantUserId: "MUID" + Date.now(),
            amount: Math.round(amount), // must be an integer in paise
            redirectUrl: `${BACKEND_URL}/payment-status/${transactionId}`,
            redirectMode: "REDIRECT",
            callbackUrl: `${BACKEND_URL}/callback`,
            paymentInstrument: {
                type: "PAY_PAGE"
            }
        };

        if (validPhone.length === 10) {
            payload.mobileNumber = validPhone;
        }

        const payloadString = JSON.stringify(payload);
        const base64Payload = Buffer.from(payloadString).toString('base64');
        
        const endpoint = "/pg/v1/pay";
        const stringToSign = base64Payload + endpoint + SALT_KEY;
        const checksum = crypto.createHash('sha256').update(stringToSign).digest('hex') + "###" + SALT_INDEX;

        const response = await axios.post(`${PHONEPE_HOST}${endpoint}`, {
            request: base64Payload
        }, {
            headers: {
                'Content-Type': 'application/json',
                'X-VERIFY': checksum,
                'accept': 'application/json'
            }
        });

        if (response.data.success) {
            const redirectUrl = response.data.data.instrumentResponse.redirectInfo.url;
            res.json({ success: true, redirectUrl });
        } else {
            res.status(400).json({ success: false, message: response.data.message });
        }
    } catch (error) {
        const phonePeError = error.response?.data || error.message;
        console.error("Payment Creation Error:", phonePeError);
        res.status(500).json({ 
            success: false, 
            message: "Payment Gateway Error: " + (phonePeError?.message || phonePeError || "Internal Server Error") 
        });
    }
});

app.get('/payment-status/:transactionId', async (req, res) => {
    const { transactionId } = req.params;
    
    try {
        const endpoint = `/pg/v1/status/${MERCHANT_ID}/${transactionId}`;
        const stringToSign = endpoint + SALT_KEY;
        const checksum = crypto.createHash('sha256').update(stringToSign).digest('hex') + "###" + SALT_INDEX;

        const response = await axios.get(`${PHONEPE_HOST}${endpoint}`, {
            headers: {
                'Content-Type': 'application/json',
                'X-VERIFY': checksum,
                'X-MERCHANT-ID': MERCHANT_ID
            }
        });

        const status = response.data.data.state; // COMPLETED, FAILED, PENDING
        await updateOrderStatus(transactionId, status);

        if (status === 'COMPLETED') {
            res.redirect(`${CLIENT_URL}/payment-success.html?txnId=${transactionId}`);
        } else {
            res.redirect(`${CLIENT_URL}/failure?txnId=${transactionId}`);
        }
    } catch (error) {
        console.error("Status Check Error:", error.response?.data || error.message);
        res.redirect(`${CLIENT_URL}/failure.html?error=status_check_failed`);
    }
});

// Webhook for Server-to-Server callbacks
app.post('/callback', async (req, res) => {
    try {
        if (!req.body.response) return res.status(400).send("No response body");
        const base64Response = req.body.response;
        const decodedResponse = Buffer.from(base64Response, 'base64').toString('utf-8');
        const responseObj = JSON.parse(decodedResponse);
        
        const transactionId = responseObj.data.merchantTransactionId;
        const state = responseObj.data.state;

        await updateOrderStatus(transactionId, state);

        console.log(`PhonePe Callback received for ${transactionId}: ${state}`);
        res.status(200).send("OK");
    } catch (error) {
        console.error("Callback Error:", error.message);
        res.status(500).send("Error");
    }
});

// Export the Express app as a Firebase Cloud Function named "api"
exports.api = onRequest({ maxInstances: 10, cors: true }, app);
